import Alu from "./ALU.js";
import IOUnit from "./IO_Unit";
import MC from "./MC.js";
import Sequenceur from "./Sequencer.js";
import Queue from "./Queue.js";
import AddressingModes from "./Adressing.js";
import { generalPurposeRegister,Register } from "./Register.js";
export let mess=[];
export let memory=new MC();
let sequenceur=new Sequenceur();
let queue = new Queue();
let ioUnit = new IOUnit();
let addressingModes=new AddressingModes();
let IP=new Register();
let R1= new generalPurposeRegister();
let R2=new generalPurposeRegister();
let R3=new generalPurposeRegister();
let R4=new Register();
let BR=new Register();
let IR=new Register();
let SR=new Register();
let Alu1=new Alu();
let Registers=[R1,R2,R3,R4,Alu1.Acc,BR,IR,SR];
export {BR,IR,Registers,queue,addressingModes,Alu1,IP,ioUnit,sequenceur};